### PR TITLE
update infrastructure

### LINKED ISSUE #62: require wp-cli v1.2.1

### PR DESCRIPTION
**Pull request by diggy**
closes #62

### CODE REVIEW

**Comment by szepeviktor** [comment]
`composer install` is missing

**Comment by diggy** [comment]
where?

**Comment by diggy** [comment]
@szepeviktor so, this is a bug in `wp-cli/scaffold-package-command`?

**Comment by szepeviktor** [comment]
> so, this is a bug in wp-cli/scaffold-package-command?

Yes.

**Pull request merged**
