### PR TITLE
Drop incompatible PHP versions

### PR DESCRIPTION
**Pull request by szepeviktor**
> symfony/filesystem 3.0.x-dev requires php >=5.5.9

### CODE REVIEW

**Comment by szepeviktor** [comment]
@diggy Have you seen this one?

**Comment by diggy** [comment]
@szepeviktor Yes, in fact I'd like to improve support rather than drop it, cf. Chouby's effort with Polylang proper to reflect WP's min req. Could you explain exactly why WP-CLI core is able to run on 5.3 and this package would require 5.5.9 or higher (apart from the fact that it's currently using traits, incompatible syntax etc)?

**Comment by szepeviktor** [comment]
Now I see that wp-cli has an alternative dependency version
https://github.com/wp-cli/wp-cli/blob/master/composer.json#L33

Why Travis is trying with the higher, incompatible one on PHP 5.3/5.4???
https://travis-ci.org/diggy/polylang-cli/jobs/241538140#L193

**Comment by szepeviktor** [comment]
I've started an UpCould instance with Debian 7 with PHP 5.4:

```
root@ppp:~# composer require wp-cli/wp-cli:dev-master
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 50 installs, 0 updates, 0 removals
  - Installing wp-cli/autoload-splitter (v0.1.3): Downloading (100%)
  - Installing wp-cli/php-cli-tools (v0.11.2): Downloading (100%)
  - Installing wp-cli/mustangostang-spyc (0.6.3): Downloading (100%)
  - Installing composer/semver (1.4.2): Downloading (100%)
  - Installing mustache/mustache (v2.11.1): Downloading (100%)
  - Installing ramsey/array_column (1.1.3): Downloading (100%)
  - Installing rmccue/requests (v1.7.0): Downloading (100%)
  - Installing symfony/filesystem (v2.8.22): Downloading (100%)
```

**Comment by szepeviktor** [comment]
Maybe composer is badly caching on Travis?
https://travis-ci.org/diggy/polylang-cli/jobs/241538140#L179

**Comment by szepeviktor** [comment]
Or old composer version is forced?
https://travis-ci.org/diggy/polylang-cli/jobs/241538140#L155

But
> Composer requires PHP 5.3.2+ to run.

https://getcomposer.org/doc/00-intro.md#system-requirements

**Comment by szepeviktor** [comment]
Let's see! https://travis-ci.org/diggy/polylang-cli/jobs/241546808

**Comment by szepeviktor** [comment]
Some traces: https://github.com/travis-ci/travis-build/pull/1064/files

**Comment by diggy** [comment]
@szepeviktor my composer-fu is rather limited, what about this:

- we're requiring `"wp-cli/wp-cli": "~1.2.1"` (cf. https://github.com/diggy/polylang-cli/blob/master/composer.json#L20)
- `"prefer-stable": true` is currently missing in composer.json

**Pull request closed without merging**
